name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti 'main' dengan nama cabang yang ingin Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GITHUB_TOKEN untuk checkout repositori

      - name: Build and Deploy
        run: |
          # Perintah untuk membangun situs dan melakukan deployment
          # Misalnya, perintah untuk menjalankan perintah Jekyll
          jekyll build --sass-dir assets/css --output _site
          
          # Ganti `jekyll build` dengan perintah sesuai kebutuhan Anda
          
          # Tambahkan perintah deployment ke GitHub Pages
          echo "Deploying to GitHub Pages..."
          # Perintah pengunggahan ke GitHub Pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan untuk memasukkan GITHUB_TOKEN di lingkungan
          # Tambahkan konfigurasi SASS sesuai kebutuhan
          SASS_DIR: 'assets/css'  # Jalur input SCSS
          OUTPUT_DIR: '_site/assets/css'  # Jalur output CSS
