name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti 'main' dengan nama cabang yang ingin Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GITHUB_TOKEN untuk checkout repositori

      - name: Build and Deploy
        # Langkah untuk membangun dan mengunggah ke GitHub Pages
        run: |
          # Tambahkan perintah untuk membangun dan mengunggah di sini
          # Misalnya, perintah untuk membangun situs statis atau mengeksekusi tugas lainnya

          # Setelah selesai membangun, gunakan perintah berikut untuk mengunggah:
          echo "Deploying to GitHub Pages..."
          # Ganti `your-deployment-command` dengan perintah pengunggahan yang Anda butuhkan

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan untuk memasukkan GITHUB_TOKEN di lingkungan
